id: A999CE443
title: 'Opening the Door to Great Bliss: An Aspiration Towards the Realm of Abhirati'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:40:19.525384
  last_modified_at: 2022-03-01 02:40:19.525390
