id: A999CE443
title: A Daily Practice of Buddha Akṣobhya
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:40:19.519189
  last_modified_at: 2022-03-01 02:40:19.519195
