id: A999CE443
title: Prayer to Akṣobhya
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:40:19.529008
  last_modified_at: 2022-03-01 02:40:19.529011
