id: A999CE443
title: 'Opening the Door to a Pure Realm: An Aspiration Towards Abhirati'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:40:19.527509
  last_modified_at: 2022-03-01 02:40:19.527512
